{
    "language": "python",
    "python": [
        "3.0",
        "3.1",
        "3.2",
        "3.3",
        "3.4",
        "3.5",
        "3.6"
    ],
    "addons": {
        "apt": {
            "packages":[
                "graphviz"
            ]
        }
    },
    "install": [
        "pip install -r requirements.txt",
        "pip install coveralls"
    ],
    "script": [
        "./coverage.sh"
    ],
    "after_success": "coveralls --rcfile=.coveragerc"
}
